server:
  port: 8001

spring:
  application:
    name: gateway-service
  cloud:
    nacos:
      server-addr: 192.168.126.54:8848
    gateway:
      routes:
        - id: item # 路由规则
          uri: lb://item-service # 目标服务，lb表示负载均衡
          predicates: # 路由断言，
            - Path=/items/**,/search/** # 请求路径作为判断
        - id: file
          uri: lb://file-service
          predicates:
            - Path=/file/**
        - id: auth
          uri: lb://auth-service
          predicates:
            - Path=/auth/**

      
