server:
  port: 8001

spring:
  application:
    name: gateway-service
  cloud:
    nacos:
      server-addr: 192.168.126.54:8848
      discovery:
        namespace: lulucar
    gateway:
      routes:
        - id: file
          uri: lb://file-service
          predicates:
            - Path=/file/**
        - id: auth
          uri: lb://auth-service
          predicates:
            - Path=/auth/**
  sa-token:
    # token名称 (同时也是cookie名称)
    token-name: satoken
    # token有效期，单位s 默认30天, -1代表永不过期 
    timeout: 604800
    # token临时有效期 (指定时间内无操作就视为token过期) 单位: 秒
    activity-timeout: -1
    # 是否允许同一账号并发登录 (为true时允许一起登录, 为false时新登录挤掉旧登录) 
    allow-concurrent-login: false
    # 在多人登录同一账号时，是否共用一个token (为true时所有登录共用一个token, 为false时每次登录新建一个token) 
    is-share: false
    # token风格
    token-style: uuid
      
