server:
  port: 8003
spring:
  application:
    name: file-service
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  cloud:
    nacos:
      server-addr: 192.168.126.54:8848
      discovery:
        namespace: lulucar
minio:
  endpoint: http://localhost:9000
  access-key: minio
  secret-key: 88888888
  bucket-name: file-lulucar
  
